### PR TITLE
Add Command to remove line breaks & trim selected content

### PR DESCRIPTION
**Pull request by Oudwins**
Hey,

Looks like my formatter did screwed something up, not sure how to avoid that... Anyways, line 62 just trims the selected text and removes all line breaks.

I do a lot of copying from PDFs and line breaks are a real issue. Im thinking this could be extended to removing HTML as well, maybe even markdown.

For those of us that at some point want to remove all formatting from text.

PS: This is my first attempt at contributing so sorry if I messed something up.

### CODE REVIEW

**Comment by argenos** [comment]
Hey @Oudwins, thanks for the PR! It's a bit hard to review since the whole file seems to have changes. Do you think you can open a new PR that contains only the changes you introduced? As a side note, are you using the plugin to extract content from PDFs?

**Comment by Oudwins** [comment]
Hello @argenos 

Will do, give me a bit more time, been super busy. Those plugins probably won't work since these are highly stylized pdfs that have multiple columns, images, side notes and footers.

**Comment by argenos** [comment]
Don't worry! Take your time!

**Comment by Oudwins** [comment]
Wow, it updated this pull request? 

Took me a long time. Been very busy (for like 5 lines of code Jesus...) but here it is. Made it to it will also remove HTML (although it uses a pretty simple regex check that wont work for a lot of things actually. Maybe its best to remove that until I can find the time to make a proper html checker.

**Comment by Oudwins** [comment]
I went ahead and deleted the regex that removed basic HTML elements. I could consider using something like this https://www.npmjs.com/package/string-strip-html for that functionality.

**Pull request merged**
